### ISSUE TITLE
Exception after adding field to node

### ISSUE THREAD

**Issue by Eternity-Yarr** [roadiz/roadiz#126]
I believe it's somehow related to the fact that field had non-latin name. 

```
An exception occurred while executing 'SELECT n0_.id AS id0, n0_.created_at AS created_at1, n0_.updated_at AS updated_at2, n0_.position AS position3, n0_.node_name AS node_name4, n0_.dynamic_node_name AS dynamic_node_name5, n0_.home AS home6, n0_.visible AS visible7, n0_.status AS status8, n0_.locked AS locked9, n0_.priority AS priority10, n0_.hide_children AS hide_children11, n0_.sterile AS sterile12, n0_.children_order AS children_order13, n0_.children_order_direction AS children_order_direction14, n1_.id AS id15, n1_.title AS title16, n1_.meta_title AS meta_title17, n1_.meta_keywords AS meta_keywords18, n1_.meta_description AS meta_description19, n2_._ AS _20, n0_.nodeType_id AS nodeType_id21, n0_.parent_node_id AS parent_node_id22, n1_.discr AS discr23, n1_.node_id AS node_id24, n1_.translation_id AS translation_id25 FROM nodes n0_ INNER JOIN nodes_sources n1_ ON n0_.id = n1_.node_id LEFT JOIN ns_articles n2_ ON n1_.id = n2_.id INNER JOIN translations t3_ ON n1_.translation_id = t3_.id AND (t3_.default_translation = 1) LIMIT 20 OFFSET 0': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'n2_._' in 'field list'
Please contact your site administrator, or post an issue on Github with following informations:

#0 /var/wwwroot/psy/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/wwwroot/psy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT n0_.id A...', Array)
#2 /var/wwwroot/psy/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT n0_.id A...', Array, Array, NULL)
#3 /var/wwwroot/psy/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(286): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#4 /var/wwwroot/psy/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(794): Doctrine\ORM\Query->_doExecute()
#5 /var/wwwroot/psy/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(574): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#6 /var/wwwroot/psy/src/Roadiz/Core/Repositories/NodeRepository.php(431): Doctrine\ORM\AbstractQuery->getResult()
#7 /var/wwwroot/psy/src/Roadiz/Core/ListManagers/NodePaginator.php(103): RZ\Roadiz\Core\Repositories\NodeRepository->findBy(Array, Array, 20, 0, NULL, NULL)
#8 /var/wwwroot/psy/src/Roadiz/Core/ListManagers/EntityListManager.php(320): RZ\Roadiz\Core\ListManagers\NodePaginator->findByAtPage(Array, 1)
#9 /var/wwwroot/psy/themes/Rozier/Controllers/NodesController.php(122): RZ\Roadiz\Core\ListManagers\EntityListManager->getEntities()
#10 [internal function]: Themes\Rozier\Controllers\NodesController->indexAction(Object(RZ\Roadiz\Core\HttpFoundation\Request), NULL)
#11 /var/wwwroot/psy/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Array, Array)
#12 /var/wwwroot/psy/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(RZ\Roadiz\Core\HttpFoundation\Request), 1)
#13 /var/wwwroot/psy/src/Roadiz/Core/Kernel.php(246): Symfony\Component\HttpKernel\HttpKernel->handle(Object(RZ\Roadiz\Core\HttpFoundation\Request))
#14 /var/wwwroot/psy/index.php(61): RZ\Roadiz\Core\Kernel->runApp()
#15 {main}
```

**Comment by Eternity-Yarr** [comment]
Yeah..

```
mysql> select * from node_type_fields;
+----+--------------+----------+------+-----------------------+----------------------------------------------------------------------+----------------+------+------------+------------+---------+---------+
| id | node_type_id | position | name | label                 | description                                                          | default_values | type | min_length | max_length | indexed | visible |
+----+--------------+----------+------+-----------------------+----------------------------------------------------------------------+----------------+------+------------+------------+---------+---------+
|  1 |            1 |        1 | _    | Ð¢ÐµÐºÑÑ‚            | Ð¡Ð¾Ð´ÐµÑ€Ð¶Ð¸Ð¼Ð¾Ðµ ÑÑ‚Ð°Ñ‚ÑŒÐ¸                                    | NULL           |    4 |       NULL |       NULL |       1 |       1 |
+----+--------------+----------+------+-----------------------+----------------------------------------------------------------------+----------------+------+------------+------------+---------+---------+
1 row in set (0.00 sec)
```

**Comment by ambroisemaupate** [comment]
Good point, I didn’t imagined that problem. I’ll add a new constraint on fields name for node-type fields and custom form fields.

**Comment by Eternity-Yarr** [comment]
Im afraid that this issue isn't quite fixed yet. Tried to do the same thing with roadiz from develop branch:

```
Roadiz has lost its musicians
An exception occurred while executing 'SELECT n0_.id AS id0, n0_.title AS title1, n0_.meta_title AS meta_title2, n0_.meta_keywords AS meta_keywords3, n0_.meta_description AS meta_description4, n1_.post_title AS post_title5, n3_.content AS content6, n0_.discr AS discr7, n0_.node_id AS node_id8, n0_.translation_id AS translation_id9 FROM nodes_sources n0_ LEFT JOIN ns_posts n1_ ON n0_.id = n1_.id LEFT JOIN ns_neutral n2_ ON n0_.id = n2_.id LEFT JOIN ns_page n3_ ON n0_.id = n3_.id WHERE n0_.translation_id = ? AND n0_.node_id = ? LIMIT 1' with params [1, 2]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'n1_.post_title' in 'field list'
Please contact your site administrator, or post an issue on Github with following informations:

#0 /var/wwwroot/rdz/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/wwwroot/rdz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT n0_.id A...', Array)
#2 /var/wwwroot/rdz/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT n0_.id A...', Array, Array, NULL)
#3 /var/wwwroot/rdz/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(286): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#4 /var/wwwroot/rdz/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(794): Doctrine\ORM\Query->_doExecute()
#5 /var/wwwroot/rdz/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(646): Doctrine\ORM\AbstractQuery->execute(NULL, NULL)
#6 /var/wwwroot/rdz/src/Roadiz/Core/Repositories/NodesSourcesRepository.php(519): Doctrine\ORM\AbstractQuery->getSingleResult()
#7 /var/wwwroot/rdz/themes/Rozier/Controllers/Nodes/NodesSourcesController.php(77): RZ\Roadiz\Core\Repositories\NodesSourcesRepository->findOneBy(Array)
#8 [internal function]: Themes\Rozier\Controllers\Nodes\NodesSourcesController->editSourceAction(Object(RZ\Roadiz\Core\HttpFoundation\Request), '2', '1')
#9 /var/wwwroot/rdz/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Array, Array)
#10 /var/wwwroot/rdz/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(RZ\Roadiz\Core\HttpFoundation\Request), 1)
#11 /var/wwwroot/rdz/src/Roadiz/Core/Kernel.php(246): Symfony\Component\HttpKernel\HttpKernel->handle(Object(RZ\Roadiz\Core\HttpFoundation\Request))
#12 /var/wwwroot/rdz/index.php(61): RZ\Roadiz\Core\Kernel->runApp()
#13 {main}
```

**Comment by azokal** [comment]
Did you delete and recreate a nodetype ?

**Comment by ambroisemaupate** [comment]
I think that once your field has been created, you’ll have to delete it manually. Just delete :
* your node_type_field entry in database
* delete field in `gen-src/GeneratedNodesSources/YourType.php`
* execute `bin/roadiz core:sources --regenerate;`
* then `bin/roadiz orm:schema-tool:update --force;`

That should clean your database.

**Comment by Eternity-Yarr** [comment]
I deleted everything :) and dropped database as well. Installed new version from scratch.

**Comment by ambroisemaupate** [comment]
Roadiz let you use a non-latin field name again ?

**Comment by ambroisemaupate** [comment]
It should show you this message (in english :-))

![capture d ecran 2015-03-30 a 11 59 32](https://cloud.githubusercontent.com/assets/380026/6894249/4a9c687e-d6d4-11e4-8718-c7b00d3ec5ec.png)

**Comment by Eternity-Yarr** [comment]
Nope, but i tried.

```
mysql> select * from node_type_fields;
+----+--------------+----------+--------------+---------------------------------------+------------------------------------------------------------------+----------------+------+------------+------------+---------+---------+
| id | node_type_id | position | name         | label                                 | description                                                      | default_values | type | min_length | max_length | indexed | visible |
+----+--------------+----------+--------------+---------------------------------------+------------------------------------------------------------------+----------------+------+------------+------------+---------+---------+
|  1 |            1 |        0 | content      | Content                               | NULL                                                             | NULL           |    4 |       NULL |       NULL |       0 |       1 |
|  2 |            1 |        0 | header_image | Header image                          | NULL                                                             | NULL           |    9 |       NULL |       NULL |       0 |       1 |
|  3 |            1 |        0 | pictures     | Pictures                              | NULL                                                             | NULL           |    9 |       NULL |       NULL |       0 |       1 |
|  4 |            3 |        1 | post_title   | Ð—Ð°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº                    | Ð—Ð°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº ÑÑ‚Ð°Ñ‚ÑŒÐ¸                                  | NULL           |    0 |          5 |       NULL |       1 |       1 |
+----+--------------+----------+--------------+---------------------------------------+------------------------------------------------------------------+----------------+------+------------+------------+---------+---------+
4 rows in set (0.00 sec)
```

**Comment by ambroisemaupate** [comment]
I think your database schema is not synced with your node. Can you share the output of `select * from ns_posts` ?

**Comment by Eternity-Yarr** [comment]
ns_posts is empty.
```
mysql> select * from ns_posts;
Empty set (0.00 sec)

mysql> show create table ns_posts;
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table    | Create Table                                                                                                                                                                                                                                    |
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ns_posts | CREATE TABLE `ns_posts` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_CE645093BF396750` FOREIGN KEY (`id`) REFERENCES `nodes_sources` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by ambroisemaupate** [comment]
Yes this is it. What does this output ? `bin/roadiz orm:schema-tool:update --dump-sql;`

**Comment by Eternity-Yarr** [comment]
```
$ bin/roadiz orm:schema-tool:update --dump-sql
ALTER TABLE ns_posts ADD post_title VARCHAR(255) DEFAULT NULL;
CREATE INDEX post_title_idx ON ns_posts (post_title);
```

**Comment by ambroisemaupate** [comment]
Great, now execute `bin/roadiz orm:schema-tool:update --force;` That should resolve your issue.

**Comment by Eternity-Yarr** [comment]
Yeah.. You're right.

**Comment by Eternity-Yarr** [comment]
According to log:
```
|  5 |       1 |           NULL | Node-type field post_title has been created.                                                                                 |     6 | 2015-03-30 12:51:01 | 127.0.0.1 |
|  6 |       1 |           NULL | Database schema has been updated.                                                                                            |     6 | 2015-03-30 12:51:02 | 127.0.0.1 |
```

**Comment by ambroisemaupate** [comment]
Maybe the process did not go well. Normally, when you add a field or a new node-type:

* Roadiz regenerate a new NodesSource class in `/gen-src/GeneratedNodesSources`.
* This PHP class is read by Doctrine annotation engine in order to perform database migrations
* Then Doctrine update your database schema.

If Roadiz did perform the schema update **before** regenerating your Node-type class, it updated database with no changes.
