### ISSUE TITLE
Impossible to delete a custom-form field if it already contains any answers. (foreign key)

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/roadiz#138]

**Comment by ambroisemaupate** [comment]
```
[2015-05-04 16:54:32] roadiz.EMERGENCY: An exception occurred while executing 'DELETE FROM custom_form_fields WHERE id = ?' with params [3]:  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`arald-www`.`custom_form_field_attributes`, CONSTRAINT `FK_B71336057F13CC0F` FOREIGN KEY (`custom_form_field_id`) REFERENCES `custom_form_fields` (`id`)) {"trace":"
#0 /var/www/vhosts/www.xxxxxxx.org/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
#1 /var/www/vhosts/www.xxxxxxx.org/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'DELETE FROM cus...', Array)
#2 /var/www/vhosts/www.xxxxxxxxx.org/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM cus...', Array, Array)
#3 /var/www/vhosts/www.xxxxxxx.org/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\\DBAL\\Connection->delete('custom_form_fie...', Array, Array)
#4 /var/www/vhosts/www.xxxxxxx.org/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->delete(Object(RZ\\Roadiz\\Core\\Entities\\CustomFormField))
#5 /var/www/vhosts/www.xxxxxxxxx.org/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\\ORM\\UnitOfWork->executeDeletions(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))
#6 /var/www/vhosts/www.xxxxxxxxxx.org/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\\ORM\\UnitOfWork->commit(NULL)
#7 /var/www/vhosts/www.xxxxxxxxx.org/htdocs/themes/Rozier/Controllers/CustomFormFieldsController.php(209): Doctrine\\ORM\\EntityManager->flush()
#8 [internal function]: Themes\\Rozier\\Controllers\\CustomFormFieldsController->deleteAction(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request), '3')
#9 /var/www/vhosts/www.xxxxxxxx.org/htdocs/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Array, Array)
#10 /var/www/vhosts/www.xxxxxxxx.org/htdocs/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request), 1)
#11 /var/www/vhosts/www.xxxxxxxxx.org/htdocs/src/Roadiz/Core/Kernel.php(232): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request))
#12 /var/www/vhosts/www.xxxxxxxxx.org/htdocs/index.php(61): RZ\\Roadiz\\Core\\Kernel->runApp()\n#13 {main}","exception":"Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException"} 
```
