### ISSUE TITLE
There was an error installing the standard version.

### ISSUE THREAD

**Issue by ziselive** [roadiz/roadiz#278]
Nothing to install or update
Generating autoload files
> php bin/roadiz composer:post-update
Do you want to copy default configuration file? [Y/n]

  [Symfony\Component\Console\Exception\RuntimeException]
  Aborted

composer:post-update [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|
--env ENV] [--preview] [--no-debug] [--] <command>

Script php bin/roadiz composer:post-update handling the post-update-cmd event returned with error code 1

**Comment by ambroisemaupate** [comment]
Hi @ziselive Are you developing on Windows?

**Comment by ziselive** [comment]
Yes, use wamp.

**Comment by ambroisemaupate** [comment]
It can be an issue with line endings. https://stackoverflow.com/questions/37709966/symfony-interactive-command-test-ends-with-runtimeexception

**Comment by ziselive** [comment]
Program in the Linux server can be installed, but the WIN platform has too many syntax errors ...

**Comment by ambroisemaupate** [comment]
Could you copy here some error examples? What is your PHP version on your WAMP server ?

**Comment by ziselive** [comment]
This problem occurs with the WAMP installer:
php bin/roadiz composer:post-update
Do you want to copy default configuration file? [Y/n]
[Symfony\Component\Console\Exception\RuntimeException]
Aborted
and...
I am using LINUX to download all the required installation and then move to the WAMP installation to display a lot of syntax errors.
I have deleted the program, and so on later to provide the wrong example.
php 5.6.30   apache2.4.25

**Comment by ziselive** [comment]
( ! ) Parse error: syntax error, unexpected ':', expecting ';' or '{' in E:\www\no\vendor\doctrine\cache\lib\Doctrine\Common\Cache\CacheProvider.php on line 192
--


1 | 0.0040 | 132856 | {main}( ) | ...\index.php:0
2 | 0.4680 | 1236408 | RZ\Roadiz\Core\Kernel->handle( ) | ...\index.php:47
3 | 0.6190 | 1825976 | RZ\Roadiz\Core\Kernel->initEvents( ) | ...\Kernel.php:248
4 | 0.6580 | 1862488 | Pimple\Container->offsetGet( ) | ...\Kernel.php:261
5 | 0.6580 | 1862504 | RZ\Roadiz\Core\Services\RoutingServiceProvider->RZ\Roadiz\Core\Services\{closure}( ) | ...\Container.php:113
6 | 0.7230 | 1906480 | Pimple\Container->offsetGet( ) | ...\Container.php:160
7 | 0.7230 | 1906536 | RZ\Roadiz\Core\Services\RoutingServiceProvider->RZ\Roadiz\Core\Services\{closure}( ) | ...\Container.php:113
8 | 0.8180 | 1976384 | Pimple\Container->offsetGet( ) | ...\Container.php:81
9 | 0.8180 | 1976432 | RZ\Roadiz\Core\Services\LoggerServiceProvider->RZ\Roadiz\Core\Services\{closure}( ) | ...\Container.php:113
10 | 0.8410 | 2057720 | Pimple\Container->offsetGet( ) | ...\Container.php:154
11 | 0.8410 | 2057896 | RZ\Roadiz\Core\Services\LoggerServiceProvider->RZ\Roadiz\Core\Services\{closure}( ) | ...\Container.php:113
12 | 0.8750 | 2125352 | Pimple\Container->offsetGet( ) | ...\Container.php:120
13 | 0.8760 | 2125752 | RZ\Roadiz\Core\Services\DoctrineServiceProvider->RZ\Roadiz\Core\Services\{closure}( ) | ...\Container.php:113
14 | 0.9041 | 2268728 | Pimple\Container->offsetGet( ) | ...\Container.php:213
15 | 0.9041 | 2268840 | RZ\Roadiz\Core\Services\DoctrineServiceProvider->RZ\Roadiz\Core\Services\{closure}( ) | ...\Container.php:113
16 | 0.9111 | 2293216 | Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration( ) | ...\DoctrineServiceProvider.php:192
17 | 0.9111 | 2293392 | Doctrine\ORM\Tools\Setup::createConfiguration( ) | ...\Setup.php:71
18 | 0.9211 | 2310320 | spl_autoload_call ( ) | ...\Setup.php:134
19 | 0.9211 | 2310368 | Composer\Autoload\ClassLoader->loadClass( ) | ...\Setup.php:134

...

**Comment by ambroisemaupate** [comment]
It’s a library dependency issue. Doctrine Cache already use PHP 7 return types. You are still in PHP 5.6. I’ll try to find why.

**Comment by ambroisemaupate** [comment]
OK I’ll have to fix doctrine/cache version. Doctrine version constraint is too loose and it downloads version 1.7 which is PHP 7.1 only

Quick fix is to add this line to your `composer.json` : 

```
"doctrine/cache":              "~1.6.2"
```

**Comment by ziselive** [comment]
Web site can only visit the home page, the other pages need to be added in the domain name /index.php/ can be a normal visit?

**Comment by ambroisemaupate** [comment]
You need to activate your apache `rewrite mod` and add some config to your virtual host to enable frontend controller pattern. https://github.com/roadiz/roadiz/blob/master/samples/apache.conf#L75

**Comment by ambroisemaupate** [comment]
https://github.com/roadiz/standard-edition/blob/master/samples/apache.conf#L75 for standard-edition

**Comment by ziselive** [comment]
I use the development version.....

**Comment by ziselive** [comment]
it's working thanks

**Comment by ziselive** [comment]
Click on
The latest updated node source, display 500 Roadiz has lost its musicians

**Comment by ambroisemaupate** [comment]
Are you on dev.php mode? Check your roadiz log. I can’t help you at all if you don’t provide me with minimum details.

**Comment by ziselive** [comment]
Basic Block
 598d514d56432
Aug 11, 2017, 2:40 PM
Has not modified dev.php

**Comment by ambroisemaupate** [comment]
This is not a log entry. Check your `logs/roadiz_prod.log` and search for the latest roadiz.EMERGENCY entry and paste the line here.

**Comment by ziselive** [comment]
[2017-08-11 23:03:48] roadiz.EMERGENCY: Parameter "newsletterId" for route "newslettersEditPage" must match "[0-9]+" ("" given) to generate a corresponding URL. {"trace":"#0 /home/wwwroot/ro/cache/prod/routing/StaticUrlGenerator.php(264): Symfony\\Component\\Routing\\Generator\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'newslettersEdit...', 1, Array, Array)\n#1 /home/wwwroot/ro/vendor/symfony/routing/Router.php(244): StaticUrlGenerator->generate('newslettersEdit...', Array, 1)\n#2 /home/wwwroot/ro/vendor/symfony-cmf/routing/ChainRouter.php(233): Symfony\\Component\\Routing\\Router->generate('newslettersEdit...', Array, 1)\n#3 /home/wwwroot/ro/vendor/symfony/twig-bridge/Extension/RoutingExtension.php(52): Symfony\\Cmf\\Component\\Routing\\ChainRouter->generate('newslettersEdit...', Array, 1)\n#4 /home/wwwroot/ro/cache/prod/twig_cache/7c/7cc89af2cf2a1ac931cecb0db241285944f240abb93665d78d9b666a6f714130.php(67): Symfony\\Bridge\\Twig\\Extension\\RoutingExtension->getPath('newslettersEdit...', Array)\n#5 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_dcb9d7f94916d818d678d0ddea590a6c178bf655bab0cce384ff1e2c2787f15e->doDisplay(Array, Array)\n#6 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#7 /home/wwwroot/ro/cache/prod/twig_cache/7d/7d224c351272e1e2ce64ab0a5a7b1ddd56b1d5ceb65ac2144728af0ae41916e3.php(42): Twig_Template->display(Array)\n#8 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_02d66eced7aa0ca4c5a6b50b826b1f07ed83d4ece1e1a05b23fee89b0a919cf1->block_content(Array, Array)\n#9 /home/wwwroot/ro/cache/prod/twig_cache/32/32c2e24dacc3b62c57ea92e68ec4295456af0d286a1a47e82c97b8faae015216.php(186): Twig_Template->displayBlock('content', Array, Array)\n#10 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_c07a7b3a98b4e8329402700042e1a218259f04bca5012e04355e193bb2bea489->doDisplay(Array, Array)\n#11 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#12 /home/wwwroot/ro/cache/prod/twig_cache/7d/7d224c351272e1e2ce64ab0a5a7b1ddd56b1d5ceb65ac2144728af0ae41916e3.php(31): Twig_Template->display(Array, Array)\n#13 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_02d66eced7aa0ca4c5a6b50b826b1f07ed83d4ece1e1a05b23fee89b0a919cf1->doDisplay(Array, Array)\n#14 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#15 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)\n#16 /home/wwwroot/ro/vendor/twig/twig/lib/Twig/Environment.php(362): Twig_Template->render(Array)\n#17 /home/wwwroot/ro/src/Roadiz/CMS/Controllers/AppController.php(311): Twig_Environment->render('@Rozier/nodes/e...', Array)\n#18 /home/wwwroot/ro/themes/Rozier/Controllers/Nodes/NodesSourcesController.php(171): RZ\\Roadiz\\CMS\\Controllers\\AppController->render('@Rozier/nodes/e...', Array)\n#19 [internal function]: Themes\\Rozier\\Controllers\\Nodes\\NodesSourcesController->editSourceAction(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request), '12', '1')\n#20 /home/wwwroot/ro/vendor/symfony/http-kernel/HttpKernel.php(144): call_user_func_array(Array, Array)\n#21 /home/wwwroot/ro/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request), 1)\n#22 /home/wwwroot/ro/src/Roadiz/Core/Kernel.php(250): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request), 1, true)\n#23 /home/wwwroot/ro/index.php(47): RZ\\Roadiz\\Core\\Kernel->handle(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request))\n#24 {main}","exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException"} {"url":"/rz-admin/nodes/edit/12/source/1","ip":"106.114.77.155","http_method":"GET","server":"ro.lidaoad.com","referrer":"http://ro.lidaoad.com/rz-admin/nodes/edit/12/source/1","locale":"en"}

**Comment by ambroisemaupate** [comment]
This is due to a change in Roadiz API, just empty your app cache. Hit `http://ro.lidaoad.com/clear_cache.php`

**Comment by ziselive** [comment]
Click on Empty trash, also show 500 Roadiz has lost its musicians.

roadiz.EMERGENCY: An exception occurred while executing 'DELETE FROM nodes WHERE id = ?' with params [10]:  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`ro`.`newsletters`, CONSTRAINT `FK_8ECF000C460D9FD7` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`)) {"trace":"#0 /home/wwwroot/ro/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 /home/wwwroot/ro/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1015): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'DELETE FROM nod...', Array)\n#2 /home/wwwroot/ro/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(596): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM nod...', Array, Array)\n#3 /home/wwwroot/ro/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\\DBAL\\Connection->delete('nodes', Array, Array)\n#4 /home/wwwroot/ro/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1094): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->delete(Object(RZ\\Roadiz\\Core\\Entities\\Node))\n#5 /home/wwwroot/ro/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\\ORM\\UnitOfWork->executeDeletions(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))\n#6 /home/wwwroot/ro/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\\ORM\\UnitOfWork->commit(NULL)\n#7 /home/wwwroot/ro/themes/Rozier/Controllers/Nodes/NodesController.php(555): Doctrine\\ORM\\EntityManager->flush()\n#8 [internal function]: Themes\\Rozier\\Controllers\\Nodes\\NodesController->emptyTrashAction(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request))\n#9 /home/wwwroot/ro/vendor/symfony/http-kernel/HttpKernel.php(144): call_user_func_array(Array, Array)\n#10 /home/wwwroot/ro/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request), 1)\n#11 /home/wwwroot/ro/src/Roadiz/Core/Kernel.php(250): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request), 1, true)\n#12 /home/wwwroot/ro/index.php(47): RZ\\Roadiz\\Core\\Kernel->handle(Object(RZ\\Roadiz\\Core\\HttpFoundation\\Request))\n#13 {main}","exception":"Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException"} {"url":"/rz-admin/nodes/empty-trash","ip":"106.114.77.155","http_method":"POST","server":"ro.lidaoad.com","referrer":"http://ro.lidaoad.com/rz-admin/nodes/empty-trash","locale":"en"}

**Comment by ambroisemaupate** [comment]
You did not perform your SQL migrations when upgrading to Roadiz 0.20. 

`bin/roadiz orm:schema-tool:update --dump-sql` then
`bin/roadiz orm:schema-tool:update --dump-sql --force`

**Comment by ziselive** [comment]
Does not seem to change.
Is my installation problem?
I downloaded the .zip installation package, and then use the composer installation to download all the required files, and finally with / install.php to install.

**Comment by ziselive** [comment]
php bin/roadiz cache:clear-fpm -e prod
Cannot GET http://localhost/clear_cache.php [404]

**Comment by ziselive** [comment]
Does not seem to change.....

**Comment by ziselive** [comment]
Nothing to update - your database is already in sync with the current entity metadata.

**Comment by ziselive** [comment]
I test again, this problem occurs when using Composer installation.
Cannot GET http://localhost/clear_cache.php [404]

**Comment by ziselive** [comment]
I have solved this problem. It is a matter of system authority.

**Comment by andresrex** [comment]
This solved this issues: https://bolt.cm/item/fixing-issues-after-the-recent-doctrine-2-6-update, just need to add to composer.json the following:

```
	"config": {
		"platform": {
			"php": "5.6"
		}
	}
```
